#!/bin/sh

# kate
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Anotações|g;s|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/org.kde.kate.desktop
 
# compton
if [ "$(grep NotShowIn /usr/share/applications/compton-conf.desktop)" = "" ] && [ -e "/usr/share/applications/compton-conf.desktop" ]; then
    echo 'NotShowIn=KDE' >> /usr/share/applications/compton-conf.desktop
fi
#sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Efeitos de janelas (Compton)|g;s|Comment\[pt\]=.*|Comment[pt]=|g;s|GenericName\[pt\]=.*|GenericName[pt]=|g' /usr/share/applications/compton-conf.desktop


# pcmanfm-qt-desktop e pcmanfm-qt-desktop-pref
if [ "$(grep NotShowIn /usr/share/applications/pcmanfm-qt-desktop-pref.desktop)" = "" ] && [ -e "/usr/share/applications/pcmanfm-qt.desktop" ]; then
    echo 'NotShowIn=KDE' >> /usr/share/applications/pcmanfm-qt-desktop-pref.desktop
    echo 'NotShowIn=KDE' >> /usr/share/applications/pcmanfm-qt.desktop
fi

# kdenlive
sed -i 's|Exec=kdenlive|Exec=QT_QUICK_BACKEND="" kdenlive|g' /usr/share/applications/org.kde.kdenlive.desktop

# steam
sed -i 's|Steam (Runtime)|Steam|g;s|Categories=Network;FileTransfer;Game;|Categories=Game;|g' /usr/share/applications/steam.desktop


#Gufw
sed -i 's|Name=.*|Name=Firewall|g;s|Categories=.*|Categories=System|g' /usr/share/applications/gufw.desktop
sed -i 's|pkexec gufw-pkexec|pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY gufw-pkexec|g' /usr/bin/gufw

# obconf-qt
if [ "$(grep NotShowIn /usr/share/applications/obconf-qt.desktop)" = "" ] && [ -e "/usr/share/applications/obconf-qt.desktop" ]; then
    echo 'NotShowIn=KDE' >> /usr/share/applications/obconf-qt.desktop
fi


# xscreensaver-properties
if [ "$(grep NotShowIn /usr/share/applications/xscreensaver-properties.desktop)" = "" ] && [ -e "/usr/share/applications/xscreensaver-properties.desktop" ]; then
    echo 'NotShowIn=KDE' >> /usr/share/applications/xscreensaver-properties.desktop
fi


# KDE connect
if [ "$(grep 'NoDisplay=true' /usr/share/applications/org.kde.kdeconnect_open.desktop)" = "" ]; then
    sed -i 's|Configurações do ||g' /usr/share/applications/org.kde.kdeconnect.kcm.desktop

    sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/org.kde.kdeconnect.sms.desktop
    
    sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/org.kde.kdeconnect_open.desktop

    sed -i 's|kdeconnect-app|kdeconnect-settings|g;s|Name\[pt_BR\]=.*|Name[pt_BR]=Interagir com dispositivos Android|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g;s|Categories=Qt;KDE;Network|Categories=Qt;KDE;Utility|g;' /usr/share/applications/org.kde.kdeconnect.app.desktop
fi

# network manager
sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/nm-connection-editor.desktop 

# ipython
sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/ipython.desktop

# imagemagick
sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/display-im6.q16.desktop

# libreoffice
sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/libreoffice-startcenter.desktop

# urxvt
sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/urxvtc.desktop
sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/urxvt.desktop
sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/urxvt-tabbed.desktop

# libreoffice xsltfilter
if [ "$(grep -c 'Name\[pt_BR\]=' /usr/lib/libreoffice/share/xdg/xsltfilter.desktop)" = "0" ] && [ -e "/usr/lib/libreoffice/share/xdg/xsltfilter.desktop" ]; then
	cp -f /usr/share/biglinux/applications-name/xsltfilter.desktop /usr/lib/libreoffice/share/xdg/xsltfilter.desktop
fi

# libreoffice math
if [ "$(grep -c 'Name\[pt_BR\]=' /usr/lib/libreoffice/share/xdg/math.desktop)" = "0" ] && [ -e "/usr/lib/libreoffice/share/xdg/math.desktop" ]; then
	cp -f /usr/share/biglinux/applications-name/math.desktop /usr/lib/libreoffice/share/xdg/math.desktop
fi

# libreoffice impress
if [ "$(grep -c 'Name\[pt_BR\]=' /usr/lib/libreoffice/share/xdg/impress.desktop)" = "0" ] && [ -e "/usr/lib/libreoffice/share/xdg/impress.desktop" ]; then
	cp -f /usr/share/biglinux/applications-name/impress.desktop /usr/lib/libreoffice/share/xdg/impress.desktop
fi

# libreoffice base
if [ "$(grep -c 'Name\[pt_BR\]=' /usr/lib/libreoffice/share/xdg/base.desktop)" = "0" ] && [ -e "/usr/lib/libreoffice/share/xdg/base.desktop" ]; then
	cp -f /usr/share/biglinux/applications-name/base.desktop /usr/lib/libreoffice/share/xdg/base.desktop
fi

# libreoffice calc
if [ "$(grep -c 'Name\[pt_BR\]=' /usr/lib/libreoffice/share/xdg/calc.desktop)" = "0" ] && [ -e "/usr/lib/libreoffice/share/xdg/calc.desktop" ]; then
	cp -f /usr/share/biglinux/applications-name/calc.desktop /usr/lib/libreoffice/share/xdg/calc.desktop
fi

# libreoffice draw
if [ "$(grep -c 'Name\[pt_BR\]=' /usr/lib/libreoffice/share/xdg/draw.desktop)" = "0" ] && [ -e "/usr/lib/libreoffice/share/xdg/draw.desktop" ]; then
	cp -f /usr/share/biglinux/applications-name/draw.desktop /usr/lib/libreoffice/share/xdg/draw.desktop
fi

# libreoffice writer
if [ "$(grep -c 'Name\[pt_BR\]=' /usr/lib/libreoffice/share/xdg/writer.desktop)" = "0" ] && [ -e "/usr/lib/libreoffice/share/xdg/writer.desktop" ]; then
	cp -f /usr/share/biglinux/applications-name/writer.desktop /usr/lib/libreoffice/share/xdg/writer.desktop
fi

# gimp
sed -i "s|Name\[pt_BR\]=Programa de manipulação de imagem do GNU|Name[pt_BR]=Editor de imagens Gimp|g" /usr/share/applications/gimp.desktop


# xscreensaver
if [ "$(grep 'Name\[pt]' /usr/share/applications/xscreensaver-properties.desktop)" = "" ] && [ -e "/usr/share/applications/xscreensaver-properties.desktop" ]; then
    echo 'Name[pt]=Protetor de tela
GenericName[pt]=
Comment[pt]=' >> /usr/share/applications/xscreensaver-properties.desktop
fi

# lxqt brightness
if [ "$(grep 'Name\[pt]' /usr/share/applications/lxqt-config-brightness.desktop)" = "" ] && [ -e "/usr/share/applications/lxqt-config-brightness.desktop" ]; then
    echo 'Name[pt]=Brilho da tela
GenericName[pt]=
Comment[pt]=' >> /usr/share/applications/lxqt-config-brightness.desktop
fi

# lxqt notificationd

sed -i "s|Name\[pt_BR\].*|Name[pt_BR]=Configurar notificações|g" /usr/share/applications/lxqt-config-notificationd.desktop

# lxqt locale
if [ "$(grep 'Name\[pt]' /usr/share/applications/lxqt-config-locale.desktop)" = "" ] && [ -e "/usr/share/applications/lxqt-config-locale.desktop" ]; then
    echo 'Name[pt]=Idioma
GenericName[pt]=
Comment[pt]=' >> /usr/share/applications/lxqt-config-locale.desktop
fi


# simple-scan
if [ "$(grep 'Name\[pt]' /usr/share/applications/simple-scan.desktop)" = "" ] && [ -e "/usr/share/applications/simple-scan.desktop" ]; then
    echo 'Name[pt]=Digitalizador de imagens
GenericName[pt]=
Comment[pt]=' >> /usr/share/applications/simple-scan.desktop
fi

# KWalletManager
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Gerenciar senhas salvas no sistema|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/org.kde.kwalletmanager5.desktop


# okular
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Visualizador de PDF, Epub e outros|g;s|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g;s|Categories=.*|Categories=Qt;KDE;Office;Viewer;|g' /usr/share/applications/org.kde.okular.desktop

# Gwenview
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Visualizador de imagens|g;s|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/org.kde.gwenview.desktop

#kmines
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Campo minado|g;s|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/org.kde.kmines.desktop

# Cheese
if [ "$(grep 'Name\[pt]=Cheese' /usr/share/applications/org.gnome.Cheese.desktop)" != "" ]; then
    sed -i 's|Name\[pt_BR\]=Cheese|Name\[pt_BR\]=Webcam|g;s|Name\[pt\]=Cheese|Name\[pt\]=Webcam|g;s|GenericName\[pt_BR\]=Cabine de webcam|GenericName\[pt_BR\]=|g;s|GenericName\[pt\]=Cabine de câmara web|GenericName\[pt\]=|g' /usr/share/applications/org.gnome.Cheese.desktop
fi

# vokoscreenNG
if [ "$(grep 'Name\[pt_BR\]=' /usr/share/applications/vokoscreenNG.desktop)" = "" ]; then
    sed -i '/Name=/a Name[pt_BR]=Gravador de tela\nComment[pt_BR]=' /usr/share/applications/vokoscreenNG.desktop
    sed -i '/Name=/a Name[pt]=Gravador de tela\nComment[pt]=' /usr/share/applications/vokoscreenNG.desktop
fi

# pavucontrol-qt
sed -i 's|multimedia-volume-control|audio-volume-high|g;s|Name\[pt\]=.*|Name[pt]=Som e microfone|g;s|GenericName\[pt\]=.*|GenericName[pt]=|g;s|Categories=.*|Categories=Settings;Audio;Mixer;Qt;|g' /usr/share/applications/pavucontrol-qt.desktop

sed -i 's|multimedia-volume-control|audio-volume-high|g'/usr/share/applications/pavucontrol-qt.desktop

# Clementine
if [ "$(grep 'Name\[pt_BR\]=Músicas' /usr/share/applications/clementine.desktop)" = "" ] && [ -e "/usr/share/applications/clementine.desktop" ]; then
    sed -i '/GenericName\[pt\]=/a Name[pt_BR]=Músicas\nGenericName[pt_BR]= \nComment[pt_BR]=' /usr/share/applications/clementine.desktop
fi

# Lutris
sed -i 's|Comment\[pt-BR\]=.*|Name[pt]=Plataforma de jogos Lutris|g;s|Comment\[id\]=.*|Comment[pt]=|g' /usr/share/applications/net.lutris.Lutris.desktop

# smplayer
sed -i "s|Name\[pt_BR\]=SMPlayer|Name[pt_BR]=Vídeos|g" /usr/share/applications/smplayer.desktop


# calculadora
if [ "$(grep 'GenericName\[pt]' /usr/share/applications/org.gnome.Calculator.desktop)" = "" ] && [ -e "/usr/share/applications/org.gnome.Calculator.desktop" ]; then
    echo 'GenericName[pt]=Calculadora' >> /usr/share/applications/org.gnome.Calculator.desktop
    echo 'Name[pt]=Calculadora' >> /usr/share/applications/org.gnome.Calculator.desktop
fi


# spectacle
sed -i 's|Name\[pt_BR\]=Spectacle|Name[pt_BR]=Utilitário de captura de tela|g;s|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/org.kde.spectacle.desktop


# compton
sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/compton.desktop

# ark
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Compactar arquivos|g;s|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/org.kde.ark.desktop

# kfind
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Procurar arquivos|g;s|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g;s|OnlyShowIn=KDE;||g' /usr/share/applications/org.kde.kfind.desktop

# discover
sed -i 's|Name\[pt_BR\]=Discover|Name[pt_BR]=Loja de aplicativos|g;s|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g;s|Categories=.*|Categories=Qt;KDE;Settings;|g' /usr/share/applications/org.kde.discover.desktop

# hardinfo
if [ "$(grep 'Comment\[pt_BR\]=' /usr/share/applications/hardinfo.desktop)" = "" ]; then
    sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Informações do Sistema|g' /usr/share/applications/hardinfo.desktop
fi

# konsole
sed -i 's|Name\[pt_BR\]=Konsole|Name[pt_BR]=Terminal|g;s|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/org.kde.konsole.desktop

# dolphin
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Gerenciar arquivos|g;s|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/org.kde.dolphin.desktop

# mintstick
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Criar pen drive de boot|g' /usr/share/applications/mintstick.desktop
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Criar pen drive de boot|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/mintstick-kde.desktop

# mintstick-format
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Formatar pen drive|g' /usr/share/applications/mintstick-format.desktop
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Formatar pen drive|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/mintstick-format-kde.desktop

# system-settings
sed -i 's|preferences-system|breeze-settings|g;' /usr/share/applications/kdesystemsettings.desktop

# ksysguard
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Gerenciar tarefas|g;s|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/org.kde.ksysguard.desktop

# gparted
if [ "$(grep 'Name\[pt]=GParted' /usr/share/applications/gparted.desktop)" != "" ]; then
    sed -i 's|GenericName\[pt_BR\]=.*||g;s|Name\[pt_BR\]=.*||g;s|GenericName\[pt\]=.*|GenericName[pt]=|g;s|Name\[pt\]=.*|Name[pt]=Formatar ou particionar|g' /usr/share/applications/gparted.desktop
fi

# onboard
rm -f /usr/share/applications/onboard-settings.desktop
if [ "$(grep 'Name\[pt]' /usr/share/applications/onboard.desktop)" = "" ] && [ -e "/usr/share/applications/onboard.desktop" ]; then
    echo 'Name[pt]=Teclado virtual
GenericName[pt]=
Comment[pt]=' >> /usr/share/applications/onboard.desktop

sed -i 's|Accessibility;||g' /usr/share/applications/onboard.desktop
fi

# baobab\
#sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Armazenamento (Baobab)|g;s|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|NotShowIn=KDE;||g' /usr/share/applications/org.gnome.baobab.desktop

# Chrome
if [ "$(grep -c 'Name\[pt_BR\]=' /usr/share/applications/google-chrome.desktop)" = "3" ]; then
    sed -i '/GenericName\[pt_BR\]=/a Name[pt_BR]=Navegador Google Chrome' /usr/share/applications/google-chrome.desktop
    sed -i 's|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/google-chrome.desktop
fi

# Brave
sed -i '/GenericName\[pt_BR\]=Navegador da Internet/a Name[pt_BR]=Navegador Brave' /usr/share/applications/brave-browser.desktop

# firefox
sed -i 's|GenericName\[pt_BR\]=.*|Name[pt_BR]=Navegador Firefox|g' /usr/share/applications/firefox.desktop

# qbittorrent
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Cliente qBittorrent|g;s|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/org.qbittorrent.qBittorrent.desktop


# kpat
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Paciência, Freecell e outros|g;s|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/org.kde.kpat.desktop

# klipper
sed -i 's|Name\[pt_BR\]=.*|Name[pt_BR]=Histórico de copiar e colar|g;s|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/org.kde.klipper.desktop

# wps-office-et
if [ "$(grep 'Name\[pt_BR\]=' /usr/share/applications/wps-office-et.desktop)" = "" ]; then
    sed -i '/GenericName=/a Name[pt_BR]=WPS Planilhas (Spreadsheets)\nGenericName[pt_BR]= \nComment[pt_BR]=' /usr/share/applications/wps-office-et.desktop
fi
rm -f /etc/xdg/menus/applications-merged/wps-office.menu

# wps-office-wpp
if [ "$(grep 'Name\[pt_BR\]=' /usr/share/applications/wps-office-wpp.desktop)" = "" ]; then
    sed -i '/GenericName=/a Name[pt_BR]=WPS Apresentações (Presentation)\nGenericName[pt_BR]= \nComment[pt_BR]=' /usr/share/applications/wps-office-wpp.desktop
fi

# wps-office-wps
if [ "$(grep 'Name\[pt_BR\]=' /usr/share/applications/wps-office-wps.desktop)" = "" ]; then
    sed -i '/GenericName=/a Name[pt_BR]=WPS Editor de textos (Writer)\nGenericName[pt_BR]= \nComment[pt_BR]=' /usr/share/applications/wps-office-wps.desktop
fi

# LXQT Menu
#rm -f /usr/share/desktop-directories/lxde-utility.directory 
#ln -s /usr/share/desktop-directories/kf5-utilities.directory /usr/share/desktop-directories/lxde-utility.directory 
#rm /usr/share/desktop-directories/lxde-settings.directory
#ln -s /usr/share/desktop-directories/kf5-settingsmenu.directory /usr/share/desktop-directories/lxde-settings.directory
#sed -i 's|<Menuname>DesktopSettings</Menuname>||g' /etc/xdg/menus/lxqt-applications.menu
#sed -i 's|Name\[ru_RU\]=.*|Name\[pt_BR\]=Configurações do LXQT|g' /usr/share/desktop-directories/lxqt-settings.directory

# Xscreensaver
sed -i 's|Categories=Settings;DesktopSettings;Security;X-XFCE;|Categories=System;DesktopSettings;Security;X-XFCE;|' /usr/share/applications/xscreensaver-properties.desktop

# Openjdk
sed -i 's|cautious-launcher %f /usr/bin/java -jar|/usr/bin/java -jar %f|' /usr/share/applications/openjdk*.desktop
if [ "$(grep 'Name\[pt_BR\]=' /usr/share/applications/openjdk-8-policytool.desktop)" = "" ]; then
    sed -i '/Name=/a Name[pt_BR]=Regras de segurança do Java\nComment[pt_BR]=' /usr/share/applications/openjdk-8-policytool.desktop
fi

# kde-wacom
sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/kde_wacom_tabletfinder.desktop

# Timeshift
if [ "$(grep -c 'Name\[pt_BR\]=' /usr/share/applications/timeshift-gtk.desktop)" = "0" ] && [ -e "/usr/share/applications/timeshift-gtk.desktop" ]; then
    sed -i '/GenericName\[ca\]=/a Name[pt_BR]=Backups e snapshots' /usr/share/applications/timeshift-gtk.desktop
    echo 'Comment[pt_BR]=' >> /usr/share/applications/timeshift-gtk.desktop
    echo 'GenericName[pt_BR]=' >> /usr/share/applications/timeshift-gtk.desktop
    sed -i 's|Comment\[pt_BR\]=.*|Comment[pt_BR]=|g;s|GenericName\[pt_BR\]=.*|GenericName[pt_BR]=|g' /usr/share/applications/timeshift-gtk.desktop
fi

# CTRL+alt+backspace
if [ "$(grep 'XKBOPTIONS=""' /etc/default/keyboard)" != "" ]; then
    sed -i 's|XKBOPTIONS=""|XKBOPTIONS="terminate:ctrl_alt_bksp"|g' /etc/default/keyboard
fi

#nvidia

sed -i 's|Name=NVIDIA X Server Settings|Name=Configure NVIDIA|g;s|System;Settings;|Settings|g;s|Comment=.*|Comment=|g' /usr/share/applications/nvidia-settings.desktop


sed -i 's|Categories=.*|Categories=Settings;|g' /usr/share/applications/org.manjaro.pamac.manager.desktop


# Yad
sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/yad-icon-browser.desktop
sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/yad-settings.desktop

# rxvt
sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/rxvt-unicode.desktop

# pcsc-tools
sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/gscriptor.desktop

# latte
sed -i 's|Categories=|NoDisplay=true\nCategories=|' /usr/share/applications/org.kde.latte-dock.desktop

